Prototype
mrc-ide/odin.js pull request #1
Opened 2019-04-09 06:49 UTC by richfitz

This sketches out the approach for the odin to js compiler.  It might eventually merge back into the main odin package (I am leaning that way at present).

Despite the apparent size of this PR, this is only 287 lines of actual code (according to codecov).

* the javascript code in inst is generated out of https://github.com/mrc-ide/dopri-js
* there's a lot of lines in the README that are just generated too
* the tests are minimal at present, but will eventually converge on the main test suite used by odin (this is one reason why this code is probably destined for odin itself - it's not easily possible to write the test suite that can be repurposed easily)

Ideally it would be great to also get feedback on the generated javascript - the README.md file contains an example of a generated model that is pretty typical

2019-05-23 15:12 UTC, weshinsley requested changes
Not many ideas - it all looks good to me, and there were just a few tiny HTML compliance things, and a couple of other very minor comments...

2019-05-23 15:12 UTC, weshinsley commented on inst/example/simple/index.html
> +    </p>
The input tags should end in /> probably - not that it really matters.

2019-05-23 15:12 UTC, weshinsley commented on inst/example/simple/index.html
> +    </p>
More html nit-picking - I don't think a `<p>` tag can contain a `<div>` tag - perhaps replace the `<p>` with `<br/>&nbsp;<br/>` or some other spacing, if that's what they're here for, (and remove `</p>`)

(Again, this doesn't matter, but I was just looking at the HTML source with Firefox and dealing with its complaints...)

2019-05-23 15:12 UTC, weshinsley commented on inst/models/sir.R
> +delta <- 1 / 5
The two examples above show the strength of this sort of modelling - beautifull minimal, clear, mathematical syntax, and `user()`. 

You could consider some bracketing on the deriv() functions - just for peasants like me who aren't very good at remembering BODMAS.

And I am disturbed by your brazen dividing of two integers (which gets the right answer in js...)

2019-05-23 15:12 UTC, weshinsley commented on inst/dopri.js
> +// in the interface really.
quit -> quite. Yep. I've even spotted a typo in your comments, such is the tremendous thoroughness of my review.

2019-05-23 15:12 UTC, weshinsley commented on inst/dopri.js
> +
Yummy... that'll teach me to click the "Load Diff" button.

2019-05-23 15:12 UTC, weshinsley commented on inst/dopri.js
> +        var it = h[0].length - 2;
I'm going to assume that you're happy for this PR, with the state of the four "TODO" comments above?

2019-06-13 14:29 UTC, richfitz commented on inst/dopri.js
> +// in the interface really.
A typo in a comment in the bundled upstream source no less - deleted here: https://github.com/mrc-ide/dopri-js/pull/4/files#diff-4349159aa3a8f26b0d335f7572d41d3eL45

2019-06-13 14:29 UTC, richfitz commented on inst/dopri.js
> +        var it = h[0].length - 2;
again these are in the bundled library...

2019-06-18 09:10 UTC, weshinsley approved these changes

2019-06-18 09:11 UTC, merged